### ISSUE TITLE
UND_ERR_CONNECT_TIMEOUT when accessing openAI

### ISSUE THREAD

**Issue by siben168** [different-ai/note-companion#295]
I can access openai, and the key i'm using is also validated, but i'm keep getting this Timeout issue, any idea what could be the cause?

I curl the openai api and responsed code 200, and I wrote a python test scripts using the exactely same .env.local file and it gets the correct results. 

Also tried set the proxy in .env.local and set the pnpm, every time got the same errors. 

# error logs
lastError: _ [AI_APICallError]: Cannot connect to API: Connect Timeout Error (attempted address: api.openai.com:443, timeout: 10000ms)
      at ef (/Users/test/python-projects/file-organizer-2000/packages/web/.next/server/chunks/7210.js:3:3482)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async ex.doStream (/Users/test/python-projects/file-organizer-2000/packages/web/.next/server/chunks/7210.js:3:14227)
      at async fn (/Users/test/python-projects/file-organizer-2000/packages/web/.next/server/chunks/7210.js:20:59979)
      at async /Users/test/python-projects/file-organizer-2000/packages/web/.next/server/chunks/7210.js:20:5352
      at async tA (/Users/test/python-projects/file-organizer-2000/packages/web/.next/server/chunks/7210.js:20:3393)
      at async n (/Users/test/python-projects/file-organizer-2000/packages/web/.next/server/chunks/7210.js:20:59118)
      at async fn (/Users/test/python-projects/file-organizer-2000/packages/web/.next/server/chunks/7210.js:20:62335)
      at async /Users/test/python-projects/file-organizer-2000/packages/web/.next/server/chunks/7210.js:20:5352
      at async h (/Users/test/python-projects/file-organizer-2000/packages/web/.next/server/app/api/(newai)/chat/route.js:33:65) {
    cause: ConnectTimeoutError: Connect Timeout Error (attempted address: api.openai.com:443, timeout: 10000ms)
        at onConnectTimeout (node:internal/deps/undici/undici:2599:28)
        at Immediate._onImmediate (node:internal/deps/undici/undici:2583:11)
        at process.processImmediate (node:internal/timers:511:21)
        at process.callbackTrampoline (node:internal/async_hooks:130:17) {
      code: 'UND_ERR_CONNECT_TIMEOUT'
    },
    url: 'https://api.openai.com/v1/chat/completions',
    requestBodyValues: {
      model: 'gpt-4o',
      logit_bias: undefined,
      logprobs: undefined,
      top_logprobs: undefined,
      user: undefined,
      parallel_tool_calls: undefined,
      max_tokens: undefined,
      temperature: 0,
      top_p: undefined,
      frequency_penalty: undefined,
      presence_penalty: undefined,
      stop: undefined,
      seed: undefined,
      max_completion_tokens: undefined,
      store: undefined,
      metadata: undefined,
      response_format: undefined,
      messages: [Array],
      tools: [Array],
      tool_choice: 'auto',
      stream: true,
      stream_options: [Object]
    },
    statusCode: undefined,
    responseHeaders: undefined,
    responseBody: undefined,
    isRetryable: true,
    data: undefined,
    [Symbol(vercel.ai.error)]: true,
    [Symbol(vercel.ai.error.AI_APICallError)]: true
  },
  [Symbol(vercel.ai.error)]: true,
  [Symbol(vercel.ai.error.AI_RetryError)]: true

**Comment by benjaminshafii** [comment]
@siben168 hmmm unsure, everything looks correct.

will try to reproduce locally.

**Comment by aexshafii** [comment]
@siben168 are you still having issues with this?
